# Generated by Django 2.2.10 on 2020-04-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200402_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp', 'title']},
        ),
    ]
