# Generated by Django 2.2.10 on 2020-04-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200402_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='previuos_post',
        ),
    ]
