# Generated by Django 2.2.10 on 2020-04-16 12:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feautured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(),
        ),
    ]
