# Generated by Django 2.2.10 on 2020-04-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200418_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postview',
        ),
    ]
